# Generated by Django 5.1.2 on 2025-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Upload an icon for this brand.",
                null=True,
                upload_to="brand_icons/",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="CSS class for the icon (e.g., 'fas fa-laptop').",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Upload an icon for this category.",
                null=True,
                upload_to="category_icons/",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="CSS class for the icon (e.g., 'fas fa-mobile-alt').",
                max_length=50,
                null=True,
            ),
        ),
    ]
