# Generated by Django 5.1.2 on 2025-01-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_brand_icon_brand_icon_class_category_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.AlterField(
            model_name="brand",
            name="icon_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
