# Generated by Django 5.1.2 on 2025-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_brand_icon_remove_category_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discountPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
