# Generated by Django 5.1.2 on 2025-01-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_product_discountprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discountPrice",
        ),
        migrations.AddField(
            model_name="product",
            name="discountPercentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
