# Generated by Django 5.1.2 on 2025-01-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_alter_shippingaddress_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
